<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Enums\ItemStatus;
use Illuminate\Support\Facades\DB;

class RestaurantLocationsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('restaurant_locations')->insert([
            [
                'restaurant_id' => 1,
                'address' => '111 Main St',
                'country_id' => 1,
                'governorate_id' => 1,
                'city_id' => 1,
                'state_id' => 1,
                'zip' => 12345,
                'latitude' => 40.7128,
                'longitude' => -74.0060,
                'opening_time' => '08:00:00',
                'closed_time' => '22:00:00',
                'closed_days' => json_encode(['Sunday']),
                'number_of_tables' => 20,
                'phone_number' => '123-456-7890',
                'mobile_number' => '098-765-4321',
                'status' => ItemStatus::Opened,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'restaurant_id' => 1,
                'address' => '222 Elm St',
                'country_id' => 1,
                'governorate_id' => 2,
                'city_id' => 2,
                'state_id' => 2,
                'zip' => 54321,
                'latitude' => 34.0522,
                'longitude' => -118.2437,
                'opening_time' => '09:00:00',
                'closed_time' => '23:00:00',
                'closed_days' => json_encode(['Monday']),
                'number_of_tables' => 30,
                'phone_number' => '234-567-8901',
                'mobile_number' => '987-654-3210',
                'status' => ItemStatus::Opened,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'restaurant_id' => 1,
                'address' => '333 Oak St',
                'country_id' => 1,
                'governorate_id' => 3,
                'city_id' => 3,
                'state_id' => 3,
                'zip' => 67890,
                'latitude' => 37.7749,
                'longitude' => -122.4194,
                'opening_time' => '07:00:00',
                'closed_time' => '21:00:00',
                'closed_days' => json_encode(['Tuesday']),
                'number_of_tables' => 25,
                'phone_number' => '345-678-9012',
                'mobile_number' => '876-543-2109',
                'status' => ItemStatus::Opened,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'restaurant_id' => 1,
                'address' => '444 Pine St',
                'country_id' => 1,
                'governorate_id' => 4,
                'city_id' => 4,
                'state_id' => 4,
                'zip' => 98765,
                'latitude' => 51.5074,
                'longitude' => -0.1278,
                'opening_time' => '10:00:00',
                'closed_time' => '20:00:00',
                'closed_days' => json_encode(['Wednesday']),
                'number_of_tables' => 15,
                'phone_number' => '456-789-0123',
                'mobile_number' => '765-432-1098',
                'status' => ItemStatus::Opened,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'restaurant_id' => 2,
                'address' => '333 Elm St',
                'country_id' => 2,
                'governorate_id' => 2,
                'city_id' => 2,
                'state_id' => 2,
                'zip' => 34321,
                'latitude' => 34.0522,
                'longitude' => -318.2437,
                'opening_time' => '03:00:00',
                'closed_time' => '23:00:00',
                'closed_days' => json_encode(['Monday']),
                'number_of_tables' => 30,
                'phone_number' => '334-567-8901',
                'mobile_number' => '387-654-3210',
                'status' => ItemStatus::Opened,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'restaurant_id' => 2,
                'address' => '444 Main St',
                'country_id' => 2,
                'governorate_id' => 1,
                'city_id' => 1,
                'state_id' => 1,
                'zip' => 12345,
                'latitude' => 40.7128,
                'longitude' => -74.0060,
                'opening_time' => '08:00:00',
                'closed_time' => '22:00:00',
                'closed_days' => json_encode(['Sunday']),
                'number_of_tables' => 20,
                'phone_number' => '103-456-7890',
                'mobile_number' => '198-765-4321',
                'status' => ItemStatus::Opened,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'restaurant_id' => 3,
                'address' => '323 Main St',
                'country_id' => 1,
                'governorate_id' => 1,
                'city_id' => 1,
                'state_id' => 1,
                'zip' => 12345,
                'latitude' => 40.7128,
                'longitude' => -74.0060,
                'opening_time' => '08:00:00',
                'closed_time' => '22:00:00',
                'closed_days' => json_encode(['Sunday']),
                'number_of_tables' => 20,
                'phone_number' => '023-456-7890',
                'mobile_number' => '919-765-4321',
                'status' => ItemStatus::Opened,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'restaurant_id' => 3,
                'address' => '544 Main St',
                'country_id' => 1,
                'governorate_id' => 1,
                'city_id' => 1,
                'state_id' => 1,
                'zip' => 12345,
                'latitude' => 40.7128,
                'longitude' => -74.0060,
                'opening_time' => '08:00:00',
                'closed_time' => '22:00:00',
                'closed_days' => json_encode(['Sunday']),
                'number_of_tables' => 20,
                'phone_number' => '123-456-7891',
                'mobile_number' => '098-765-4320',
                'status' => ItemStatus::Opened,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'restaurant_id' => 4,
                'address' => '4443 Main St',
                'country_id' => 1,
                'governorate_id' => 1,
                'city_id' => 1,
                'state_id' => 1,
                'zip' => 12345,
                'latitude' => 40.7128,
                'longitude' => -74.0060,
                'opening_time' => '08:00:00',
                'closed_time' => '22:00:00',
                'closed_days' => json_encode(['Sunday']),
                'number_of_tables' => 20,
                'phone_number' => '323-456-7890',
                'mobile_number' => '298-765-4321',
                'status' => ItemStatus::Opened,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'restaurant_id' => 5,
                'address' => '5556 Main St',
                'country_id' => 1,
                'governorate_id' => 1,
                'city_id' => 1,
                'state_id' => 1,
                'zip' => 12345,
                'latitude' => 40.7128,
                'longitude' => -74.0060,
                'opening_time' => '08:00:00',
                'closed_time' => '22:00:00',
                'closed_days' => json_encode(['Sunday']),
                'number_of_tables' => 20,
                'phone_number' => '923-456-7890',
                'mobile_number' => '898-765-4321',
                'status' => ItemStatus::Opened,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'restaurant_id' => 6,
                'address' => '666 Main St',
                'country_id' => 1,
                'governorate_id' => 1,
                'city_id' => 1,
                'state_id' => 1,
                'zip' => 12345,
                'latitude' => 40.7128,
                'longitude' => -74.0060,
                'opening_time' => '08:00:00',
                'closed_time' => '22:00:00',
                'closed_days' => json_encode(['Sunday']),
                'number_of_tables' => 20,
                'phone_number' => '333-456-7890',
                'mobile_number' => '111-765-4321',
                'status' => ItemStatus::Opened,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'restaurant_id' => 7,
                'address' => '777 Main St',
                'country_id' => 1,
                'governorate_id' => 1,
                'city_id' => 1,
                'state_id' => 1,
                'zip' => 12345,
                'latitude' => 40.7128,
                'longitude' => -74.0060,
                'opening_time' => '08:00:00',
                'closed_time' => '22:00:00',
                'closed_days' => json_encode(['Sunday']),
                'number_of_tables' => 20,
                'phone_number' => '232-456-7890',
                'mobile_number' => '987-765-4321',
                'status' => ItemStatus::Opened,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'restaurant_id' => 7,
                'address' => '77772 Main St',
                'country_id' => 1,
                'governorate_id' => 1,
                'city_id' => 1,
                'state_id' => 1,
                'zip' => 12345,
                'latitude' => 40.7128,
                'longitude' => -74.0060,
                'opening_time' => '08:00:00',
                'closed_time' => '22:00:00',
                'closed_days' => json_encode(['Sunday']),
                'number_of_tables' => 20,
                'phone_number' => '888-456-7890',
                'mobile_number' => '999-765-4321',
                'status' => ItemStatus::Opened,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'restaurant_id' => 8,
                'address' => '8881 Main St',
                'country_id' => 1,
                'governorate_id' => 1,
                'city_id' => 1,
                'state_id' => 1,
                'zip' => 12345,
                'latitude' => 40.7128,
                'longitude' => -74.0060,
                'opening_time' => '08:00:00',
                'closed_time' => '22:00:00',
                'closed_days' => json_encode(['Sunday']),
                'number_of_tables' => 20,
                'phone_number' => '777-456-7890',
                'mobile_number' => '666-765-4321',
                'status' => ItemStatus::Opened,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'restaurant_id' => 9,
                'address' => '999 Main St',
                'country_id' => 1,
                'governorate_id' => 1,
                'city_id' => 1,
                'state_id' => 1,
                'zip' => 12345,
                'latitude' => 40.7128,
                'longitude' => -74.0060,
                'opening_time' => '08:00:00',
                'closed_time' => '22:00:00',
                'closed_days' => json_encode(['Sunday']),
                'number_of_tables' => 20,
                'phone_number' => '656-456-7890',
                'mobile_number' => '574-765-4321',
                'status' => ItemStatus::Opened,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'restaurant_id' => 10,
                'address' => '1010 Main St',
                'country_id' => 1,
                'governorate_id' => 1,
                'city_id' => 1,
                'state_id' => 1,
                'zip' => 12345,
                'latitude' => 40.7128,
                'longitude' => -74.0060,
                'opening_time' => '08:00:00',
                'closed_time' => '22:00:00',
                'closed_days' => json_encode(['Sunday']),
                'number_of_tables' => 20,
                'phone_number' => '373-456-7890',
                'mobile_number' => '265-765-4321',
                'status' => ItemStatus::Opened,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
