<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use App\Enums\UserStatus;

class RestaurantsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('restaurants')->insert([
            [
                'user_id' => 1,
                'logo' => 'logos/restaurant1.png',
                'cover' => 'https://images.unsplash.com/photo-1574936145840-28808d77a0b6?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NDF8fHJlc3RhdXJhbnR8ZW58MHx8MHx8fDA%3D',
                'name' => 'The Great Restaurant',
                'slug' => str::slug('The Great Restaurant'),
                'title' => 'Best Dining Experience',
                'summary' => 'A brief summary about The Great Restaurant.',
                'description' => 'An extended description about The Great Restaurant and its offerings.',
                // 'comment_id'=>0,
                'hot_line' => '111-123-4567',
                'status' => UserStatus::Active,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'logo' => 'logos/restaurant2.png',
                'cover' => 'https://images.unsplash.com/photo-1543007631-283050bb3e8c?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8ODd8fHJlc3RhdXJhbnR8ZW58MHx8MHx8fDA%3D',
                'name' => 'Nrban Eats',
                'slug' => Str::slug('Nrban Eats'),
                'title' => 'Delicious Urban Cuisine',
                'summary' => 'A brief summary about Urban Eats.',
                'description' => 'An extended description about Urban Eats and its urban cuisine.',
                // 'comment_id'=>0,
                'hot_line' => '200-123-4567',
                'status' => UserStatus::Active,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'logo' => 'logos/restaurant3.png',
                'cover' => 'https://images.unsplash.com/photo-1602232037779-30b01ac3c457?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OTR8fHJlc3RhdXJhbnR8ZW58MHx8MHx8fDA%3D',
                'name' => 'Urban Eats',
                'slug' => Str::slug('Urban Eats'),
                'title' => '3Delicious Urban Cuisine',
                'summary' => '3A brief summary about Urban Eats.',
                'description' => '3An extended description about Urban Eats and its urban cuisine.',
                // 'comment_id'=>0,
                'hot_line' => '310-123-4567',
                'status' => UserStatus::InActive,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'logo' => '4logos/restaurant3.png',
                'cover' => 'https://images.unsplash.com/photo-1569096651661-820d0de8b4ab?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTAzfHxyZXN0YXVyYW50fGVufDB8fDB8fHww',
                'name' => '4Urban Eats',
                'slug' => Str::slug('4Urban Eats'),
                'title' => '4Delicious Urban Cuisine',
                'summary' => '4A brief summary about Urban Eats.',
                'description' => '4An extended description about Urban Eats and its urban cuisine.',
                // 'comment_id'=>0,
                'hot_line' => '840-123-4567',
                'status' => UserStatus::InActive,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'logo' => '5logos/restaurant3.png',
                'cover' => 'https://images.unsplash.com/photo-1531973819741-e27a5ae2cc7b?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTA5fHxyZXN0YXVyYW50fGVufDB8fDB8fHww',
                'name' => '5Urban Eats',
                'slug' => Str::slug('5Urban Eats'),
                'title' => '5Delicious Urban Cuisine',
                'summary' => '5A brief summary about Urban Eats.',
                'description' => '5An extended description about Urban Eats and its urban cuisine.',
                // 'comment_id'=>0,
                'hot_line' => '510-123-4567',
                'status' => UserStatus::InActive,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'logo' => '6logos/restaurant3.png',
                'cover' => 'https://images.unsplash.com/photo-1567745219000-b99afacf5ef6?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTIyfHxyZXN0YXVyYW50fGVufDB8fDB8fHww',
                'name' => '6Urban Eats',
                'slug' => Str::slug('6Urban Eats'),
                'title' => '6Delicious Urban Cuisine',
                'summary' => '6A brief summary about Urban Eats.',
                'description' => '6An extended description about Urban Eats and its urban cuisine.',
                // 'comment_id'=>0,
                'hot_line' => '610-123-4567',
                'status' => UserStatus::InActive,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'logo' => '7logos/restaurant3.png',
                'cover' => 'https://images.unsplash.com/photo-1610894803089-0c3283d8d059?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTc3fHxyZXN0YXVyYW50fGVufDB8fDB8fHww',
                'name' => '7Urban Eats',
                'slug' => Str::slug('7Urban Eats'),
                'title' => '7Delicious Urban Cuisine',
                'summary' => '7A brief summary about Urban Eats.',
                'description' => '7An extended description about Urban Eats and its urban cuisine.',
                // 'comment_id'=>0,
                'hot_line' => '710-123-4567',
                'status' => UserStatus::InActive,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'logo' => '8logos/restaurant3.png',
                'cover' => 'https://images.unsplash.com/photo-1569541372853-97033ae8983b?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTUwfHxyZXN0YXVyYW50fGVufDB8fDB8fHww',
                'name' => '8Urban Eats',
                'slug' => Str::slug('8Urban Eats'),
                'title' => '8Delicious Urban Cuisine',
                'summary' => '8A brief summary about Urban Eats.',
                'description' => '8An extended description about Urban Eats and its urban cuisine.',
                // 'comment_id'=>0,
                'hot_line' => '810-123-4567',
                'status' => UserStatus::InActive,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'logo' => '9logos/restaurant3.png',
                'cover' => 'https://images.unsplash.com/photo-1616091216791-a5360b5fc78a?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjAxfHxyZXN0YXVyYW50fGVufDB8fDB8fHww',
                'name' => '9Urban Eats',
                'slug' => Str::slug('9Urban Eats'),
                'title' => '9Delicious Urban Cuisine',
                'summary' => '9A brief summary about Urban Eats.',
                'description' => '9An extended description about Urban Eats and its urban cuisine.',
                // 'comment_id'=>0,
                'hot_line' => '910-123-4567',
                'status' => UserStatus::InActive,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'logo' => '10logos/restaurant3.png',
                'cover' => 'https://images.unsplash.com/photo-1554919428-20d72fa44a99?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mjc5fHxyZXN0YXVyYW50fGVufDB8fDB8fHww',
                'name' => '10Urban Eats',
                'slug' => Str::slug('10Urban Eats'),
                'title' => '10Delicious Urban Cuisine',
                'summary' => '10A brief summary about Urban Eats.',
                'description' => '10An extended description about Urban Eats and its urban cuisine.',
                // 'comment_id'=>0,
                'hot_line' => '100-123-4567',
                'status' => UserStatus::InActive,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}