<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use App\Enums\UserStatus;

class RestaurantsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('restaurants')->insert([
            [
                'user_id' => 1,
                'logo' => 'logos/restaurant1.png',
                'cover' => 'https://tinyurl.com/5n7nrhkp',
                'name' => 'The Great Restaurant',
                'slug' => str::slug('The Great Restaurant'),
                'title' => 'Best Dining Experience',
                'summary' => 'A brief summary about The Great Restaurant.',
                'description' => 'An extended description about The Great Restaurant and its offerings.',
                // 'comment_id'=>0,
                'hot_line' => '111-123-4567',
                'status' => UserStatus::Active,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'logo' => 'logos/restaurant2.png',
                'cover' => 'covers/restaurant2.jpg',
                'name' => 'Nrban Eats',
                'slug' => Str::slug('Nrban Eats'),
                'title' => 'Delicious Urban Cuisine',
                'summary' => 'A brief summary about Urban Eats.',
                'description' => 'An extended description about Urban Eats and its urban cuisine.',
                // 'comment_id'=>0,
                'hot_line' => '200-123-4567',
                'status' => UserStatus::Active,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'logo' => 'logos/restaurant3.png',
                'cover' => 'covers/restaurant3.jpg',
                'name' => 'Urban Eats',
                'slug' => Str::slug('Urban Eats'),
                'title' => '3Delicious Urban Cuisine',
                'summary' => '3A brief summary about Urban Eats.',
                'description' => '3An extended description about Urban Eats and its urban cuisine.',
                // 'comment_id'=>0,
                'hot_line' => '310-123-4567',
                'status' => UserStatus::InActive,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'logo' => '4logos/restaurant3.png',
                'cover' => '4covers/restaurant3.jpg',
                'name' => '4Urban Eats',
                'slug' => Str::slug('4Urban Eats'),
                'title' => '4Delicious Urban Cuisine',
                'summary' => '4A brief summary about Urban Eats.',
                'description' => '4An extended description about Urban Eats and its urban cuisine.',
                // 'comment_id'=>0,
                'hot_line' => '840-123-4567',
                'status' => UserStatus::InActive,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'logo' => '5logos/restaurant3.png',
                'cover' => '5covers/restaurant3.jpg',
                'name' => '5Urban Eats',
                'slug' => Str::slug('5Urban Eats'),
                'title' => '5Delicious Urban Cuisine',
                'summary' => '5A brief summary about Urban Eats.',
                'description' => '5An extended description about Urban Eats and its urban cuisine.',
                // 'comment_id'=>0,
                'hot_line' => '510-123-4567',
                'status' => UserStatus::InActive,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'logo' => '6logos/restaurant3.png',
                'cover' => '6covers/restaurant3.jpg',
                'name' => '6Urban Eats',
                'slug' => Str::slug('6Urban Eats'),
                'title' => '6Delicious Urban Cuisine',
                'summary' => '6A brief summary about Urban Eats.',
                'description' => '6An extended description about Urban Eats and its urban cuisine.',
                // 'comment_id'=>0,
                'hot_line' => '610-123-4567',
                'status' => UserStatus::InActive,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'logo' => '7logos/restaurant3.png',
                'cover' => '7covers/restaurant3.jpg',
                'name' => '7Urban Eats',
                'slug' => Str::slug('7Urban Eats'),
                'title' => '7Delicious Urban Cuisine',
                'summary' => '7A brief summary about Urban Eats.',
                'description' => '7An extended description about Urban Eats and its urban cuisine.',
                // 'comment_id'=>0,
                'hot_line' => '710-123-4567',
                'status' => UserStatus::InActive,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'logo' => '8logos/restaurant3.png',
                'cover' => '8covers/restaurant3.jpg',
                'name' => '8Urban Eats',
                'slug' => Str::slug('8Urban Eats'),
                'title' => '8Delicious Urban Cuisine',
                'summary' => '8A brief summary about Urban Eats.',
                'description' => '8An extended description about Urban Eats and its urban cuisine.',
                // 'comment_id'=>0,
                'hot_line' => '810-123-4567',
                'status' => UserStatus::InActive,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'logo' => '9logos/restaurant3.png',
                'cover' => '9covers/restaurant3.jpg',
                'name' => '9Urban Eats',
                'slug' => Str::slug('9Urban Eats'),
                'title' => '9Delicious Urban Cuisine',
                'summary' => '9A brief summary about Urban Eats.',
                'description' => '9An extended description about Urban Eats and its urban cuisine.',
                // 'comment_id'=>0,
                'hot_line' => '910-123-4567',
                'status' => UserStatus::InActive,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'logo' => '10logos/restaurant3.png',
                'cover' => '10covers/restaurant3.jpg',
                'name' => '10Urban Eats',
                'slug' => Str::slug('10Urban Eats'),
                'title' => '10Delicious Urban Cuisine',
                'summary' => '10A brief summary about Urban Eats.',
                'description' => '10An extended description about Urban Eats and its urban cuisine.',
                // 'comment_id'=>0,
                'hot_line' => '100-123-4567',
                'status' => UserStatus::InActive,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}